const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('browser', {
  newTab: () => ipcRenderer.send('tab:new'),
  newPrivateTab: () => ipcRenderer.send('tab:new-private'),
  closeTab: (id) => ipcRenderer.send('tab:close', id),
  activateTab: (id) => ipcRenderer.send('tab:activate', id),
  muteTab: (id) => ipcRenderer.send('tab:mute', id),
  tabContextMenu: (id) => ipcRenderer.send('tab:context', id),
  reorderTab: (id, targetId) => ipcRenderer.send('tab:reorder', { id, targetId }),
  navigate: (input) => ipcRenderer.send('nav:go', input),
  back: () => ipcRenderer.send('nav:back'),
  forward: () => ipcRenderer.send('nav:forward'),
  reload: () => ipcRenderer.send('nav:reload'),
  stop: () => ipcRenderer.send('nav:stop'),
  toggleKeepAlive: (id) => ipcRenderer.send('keepalive:toggle', id),
  toggleBookmark: () => ipcRenderer.send('bookmark:toggle'),
  toggleShield: () => ipcRenderer.send('shield:toggle'),
  openReader: () => ipcRenderer.send('reader:open'),
  togglePiP: () => ipcRenderer.send('pip:toggle'),
  openInternal: (name) => ipcRenderer.send('internal:open', name),
  openMenu: (x, y) => ipcRenderer.send('ui:menu', { x, y }),
  setChromeHeight: (h) => ipcRenderer.send('ui:chrome-height', h),
  suggest: (q) => ipcRenderer.invoke('suggest', q),
  findStart: (text) => ipcRenderer.send('find:start', text),
  findNext: (text, forward) => ipcRenderer.send('find:next', { text, forward }),
  findStop: () => ipcRenderer.send('find:stop'),
  onState: (cb) => ipcRenderer.on('state', (_e, state) => cb(state)),
  onFocusAddress: (cb) => ipcRenderer.on('focus-address', () => cb()),
  onFindOpen: (cb) => ipcRenderer.on('find:open', () => cb()),
  onFindResult: (cb) => ipcRenderer.on('find:result', (_e, r) => cb(r)),
  // upload sidebar (custom file picker)
  fsList: (dir) => ipcRenderer.invoke('fs:list', dir),
  fsPreview: (p) => ipcRenderer.invoke('fs:preview', p),
  fsFavorite: (action, path) => ipcRenderer.invoke('fs:favorite', { action, path }),
  uploadChoose: (paths) => ipcRenderer.send('upload:choose', paths),
  uploadCancel: () => ipcRenderer.send('upload:cancel'),
  onUploadOpen: (cb) => ipcRenderer.on('upload:open', (_e, d) => cb(d)),
  onUploadClose: (cb) => ipcRenderer.on('upload:close', () => cb()),
});
